version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "express"
      - dependency-name: "ffmpeg-static"
      - dependency-name: "lodash"
      - dependency-name: "ytdl-core"
    commit-message:
      prefix: "npm"
